// Low-frequency oscillator (LFO) for modulation
lfo(freq, amplitude=1, dt=10ms) = modulation |> {
    init: { phase = 0 }
    modulation = amplitude * sin(phase * 2 * pi)
    phase = fmod(phase + dt / freq, 1)
}

phasor(freq, dt=10ms) = phase |> 
{
    init: {phase = 0}
    phase = fmod(phase + dt / freq, 1)
}

pos(val) = (val + 1) * 0.5 