/*
    Idyl is a temporal, functional language for describing time, schedule events
    Its purpose is to control audio realtime systems such as live-coding audio engine (Csound, and several others)
    It is an interpreted language, and will provide two different time engine : one based on high accuracy system clocks, 
    another based on callbacks from audio engines.  

    
    The goal of the language is to be : 
    - The most expressive it can be (less characters to express more)
    - functional 
    - Designed for audio (livecoding, music composition, scheduling, control) & multimedia 
    - DSL for any use that requires accurate timing 

    This specification attempt file is written with a tentative for Idyl syntax 
*/


// Constant function definition (interpreter will compute it immediatly)
a = 1 + 3 
// Same with copy 
b = a 
// Time is a primitive 
c = 100ms
d = 1.53s 
// frequency is time 
z = 5.1hz 
// Musical time, based on main clock 
e = 1.25b
f = 0.25b 
// Define main tempo at 60 bpm (tempo is primitive)
tempo(60) 

// Create new clock at 120 bpm (clock is primitive)
c1 = clock(120) 
// Change tempo 
tempo(c1, 60)
// t1 is 1.5b time from c1 clock 
t1 = c1(1.5b) 
// Retrieve triggers of beats from a clock 
c1_trigs = beats(c1)
main_clock_trigs = beats(main_clock)
// Functions with parameters 
f(a, b) = a - b 


// Internally, interpreter will treat time as floating point milliseconds (whether it is a frequency, a musical time, or another value)
// This way, no time cast is necessary

// Temporal functions take a dt (delta time) parameter with default argument. They are only computed  
// Here, input will be the function output, sampled every 10ms 
sample_and_hold(input, dt=10ms) = input    
// Calling this function would look like this (dt parameter is optional, since it has default argument)
a = sample_and_hold( any_signal, dt=50ms )

// trigger primitive is ! character
// its behavior is to create an impulse (it will be used for modules that need scheduling, 
// or to trigger actions at certain times)
metronome(dt=50ms) = !

/* Control structures */ 

// Specific ternary operator, with infinite number of cases
// Condition is a number (0 for false, 1 for 1rst case, 2 for second etc)
// There will be no boolean primitive, only condition evaluation
some_ternary_function(cond, a, b, c) = a, b, c ? cond  


// More complex time function 
// with an update block (called lambda) executed at dt precision. Update bloc expressed with : `~> {/* update bloc here */}` 
sine_oscillator(frequency, dt=10ms) = sin(phase * 2 * pi)
~> {
    [
        // This is the init bloc, executed once at init of function call  
        phase = 0
    ]
    // Here is the update bloc, executed each dt time
    incr = 1 / frequency // frequency can change, we need to 
    phase = fmod(phase + incr, 1) // phase incrementation, modulo 1
}

// Some common use 
// dt is automatically adjusted to parent dt if not  explicitely set, so here 50ms for sine_oscillator
modulator(dt = 100ms ) = sine_oscillator(10hz) * sine_oscillator(1.5hz)

// Emission of a value by a function 
//useful for lambda functions capture 
sine_oscillator(frequency, dt=10ms) = sin(phase * 2 * pi)
~> {
    [
        phase = 0
    ]
    // The ! operator after function name indicates that function value is emitted by the parent function. 
    // Thus, it can be captured later by lambdas 
    incr = 1 / frequency // frequency can change, we need to 
    phase! = fmod(phase + incr, 1) // phase incrementation, modulo 1
}

// More complex case 
modulate(dt = 50ms) = sine_oscillator(10hz) ~> [phase] {
    amp_mod = fmod(phase * 4, 1)  
    // inp is input, corresponding to the main output of sine_oscillator
    // This < instruction means "return", thus modifying the actual sine_oscillator output
    < inp * amp_mod 
} 

/*
    We can override some part of function update statement this way 
*/
weird_oscillator(freq, random_amount, dt=10hz) = sine_oscillator(freq){
    // This is appended to the body of sine_oscillator lambda (update) 
    phase += rnd(0, random_amount)
} 

/*
    Several math primitives, based on fastmath on interpretor side
    By default, all numbers are double floating point 
*/
sin(phase)
cos(phase)
fmod(value, modulo) // modulo for floating points 
mod(value, modulo) //  integers modulo 
% operator // modulo for integers
floor(val) // returns integer part of a value
ceil(val) // returns integer part + 1 
round(val) // rounds to nearest integer 
round(val, step) // rounds to nearest step
min(a, b) // Returns minimum of both arguments 
max(a, b) // returns maximum of both arguments 
abs(a) // Returns absolute value 
pow(a, exponent) // power of exponent 
sqrt(a) // square root 
rnd() // Random between 0 and 1 
rnd(a, b) // Random between a and b 
rnd(a, b, step) // Random between a and b, rounded to step 
rint(a, b) // syntactic sugar for random integer between a and b (equivalent to `rnd(a, b, 1)` )

// Several others may be implemented later (tan, tanh, sinc, log, log10, exp, exp10 etc)



/*
    Module system for compiled libraries
    Example of a Csound module created to create and control Csound 
*/
// Retrieve the module with import primitive 
cs = import("csound")
// Compile some orchestra file 
my_orchestra = cs.compile("my_orc.orc")
// get an instrument definition 
instr = my_orchestra.get("my_instr") 
// or 
instr = my_orchestra.get(1) // for instrument 1 

// Trigger instr , and retrieve voice if needed for control 
voice = instr(0s, 5s) // Start at 0 (now) and runs for 5 secs 
// Question : what to do when voice dies after 5s : how to know that it is "dead" ? How to treat this ? 

// Another module 
osc = import("osc") 

sender = osc.sender("192.168.1.47", 8080)
sender.send(/some/thing", some_function) // fired at dt precision 
receiver = osc.receiver(8081) 

// Syntax Problem here : how to  use it (the function already has its statement) ? 
another_function = receiver ~> (address, value) {
    // Use address and value 
}


/*
    Custom idyl libraries
*/
// loaded inside custom_lib namespace 
custom_lib = lib("my_custom_lib.idl")
// loaded in global space 
lib("my_custom_lib.idl")


/* 
    Instanciation, duplication, death 
    candidates Primitives
    - `still` or `lull` for kill 
    - `twin`, `echo` `mimic` or `sprout` for duplication 

*/

running_oscillator = instr.freq( sine_oscillator(1hz, dt = 10) ) // This is running  



/*
    Flow 
    Flow is a concept for data structures, patterns etc 
*/


// Passing a generator function for a flow 
// `.` is 0 or silence (absence of trigger)
flow myflow(f) = {
    rhythm = | f(x) . . f(x) |
}

flow basic_flow() = {
    rhythm = | ! . . ! |
    // Flows members can have different sizes
    note = | 50 51 52 55 45 63 |
}

// Same with automatic generation on a range 
flow sinetable = {
    // Specify the size of table 
    sin = [256] |sin(x/N * 2*pi)|  
}

flow arp(scale, offset) = {
    note = | scale[0] + offset
             scale[2] + offset
             scale[4] + offset
             . |
}

// Combination of two flows 
// a.trig + b.trig will perform + operation of operands 
// a.note ?? b.note means it will take a if a exists at current step, b if not a but b exists, else nothing 
flow combine(a, b) = {
    trig = a.trig + b.trig
    note = a.note ?? b.note
    // concat is a primitive to concatenate flows
    dur = concat(a.dur, b.dur)
}

// With repeat bars 
// |2| means two repeats of the passed section 
flow patternize(f) = {
    // So sections are repeated this way : S1, S1, S2, S1, S1, S2, S1, S1, S3
    trig = | f(0) . f(1) |2|  f(2) f(3) . . |3| |

    // Here |2|| means it will be computed this way : S1, S1, S2, S2, S2 
    note = | 60 63 66 |2|| 40 43 |3| |
}

/*
    Several ways to read it 
*/

// 1. trigger with automatic wrap of flow members
trig_flow = basic_flow(metronome(1s))
flow_notes = trig_flow.note
flow_rhythm = trig_flow.rhythm(metronome(1s))

// 2. index  with automatic wrap of flow members

// No dt, it is triggered by metronome 
increment(trig) = index ~> {
    [index = 0]
    index += 1
}
trig_flow = basic_flow(increment(metronome(1s)))

// 3. Fractional indexing (automatically wrap to 0-1) 
// In this scenario, this allows to read different members with different sizes at same speed 
phasor(freq, dt = 10) = phase 
~> {
    [phase = 0]
    incr = 1 / freq 
    phase = fmod(phase+incr, 1) 
}

// With parenthesis, since it actually accesses the the interpreter flow function for floating points
run_flow = basic_flow(phasor(1hz))
// Or 
run_flow = basic_flow.note.(phasor(1hz))

/*
    Question : on the engine side, how to determine if flow is run through triggers, integers or float ? 
*/


// simple array access 
array_access = basic_flow.note[3] 
// This contains parallel information : note & rhythm 
array_access = basic_flow[4]
rhythm = array_access.rhythm

