/*
    Basic assignments of constant functions 
*/
a = 1 + 3
b = a 
c = 100ms
d = 1.53s 
e = 1.25b
e_2 = 1.25beat


/*
    Simple Parametrized function 
*/
osc(f, amp) = sawtooth(f) * amp

/*
    Function with update 
*/
modosc(f, amp, modfq, modamp) = sawtooth(f) 
    ~> { f = f + sawtooth(modfq) * modamp; }

/*
    Function with private scope 
*/
basic_oscillator(f, amp) = sin(freq) * amp 
    where {
        pi = 3.14;
        freq = 2 * pi * f;
    }

/*
    Complex function (update) & private scope 
*/
funkypulse(t) = pulse(t1) :: pulse(t2) :: pulse(t3)
    ~> {
        t1 = t * osc(f1);
        t2 = t * osc(f2);
        t3 = t * osc(f3);
    }
    where {
        f1 = rand() * t;
        f2 = rand() * t;
        f3 = rand() * t;
    }

/* 
    Emission tests with ! operator 
*/
emit_test(smtg) = hello(updated) ~> {updated = smtg * dt; updated!;}
/*
//This doesnt parse (updated! = smtg)
emit_test(smtg) = hello(updated) ~> {updated! = smtg * dt;}
*/