// idyl.cpp - Idyl language parser main driver

#include <iostream>
#include <fstream>
#include <sstream>
#include <memory>
#include "parser/ast.hpp"
#include "parser/idyl_lexer.hpp"
#include "parser/idyl.tab.hh"
#include "semantic/analyzer.hpp"

// Forward declaration of global parsed program (defined in idyl.y)
extern std::shared_ptr<idyl::parser::program> g_program;

// Lexer function (generated by Flex, declared in idyl.y)
namespace yy {
    parser::symbol_type yylex(lexer& driver);
}

static void print_usage(const char* prog) {
    std::cerr << "Usage: " << prog << " [file.idyl] [options]\n"
              << "  - If no file is given, reads from stdin.\n"
              << "  - Use '-' as filename to force stdin.\n"
              << "  - Options:\n"
              << "    --trace    Enable parser/lexer debug tracing\n";
}

int main(int argc, char** argv) {
    std::istream* input = nullptr;
    std::ifstream file_stream;
    bool trace = false;

    idyl::semantic::analyzer analyzer; 

    // Parse command-line arguments
    if (argc > 1 && std::string(argv[1]) != "-") {
        // Open file
        file_stream.open(argv[1]);
        if (!file_stream.is_open()) {
            std::cerr << "Error: Could not open file '" << argv[1] << "'" << std::endl;
            print_usage(argv[0]);
            return 1;
        }
        input = &file_stream;
    } else {
        // Read from stdin
        input = &std::cin;
    }

    // Check for --trace option
    if (argc > 2 && std::string(argv[2]) == "--trace") {
        trace = true;
    }

    // Create lexer and parser
    yy::lexer lex(*input);
    yy::parser parser_obj(lex);

    // Enable debug tracing if requested
    if (trace) {
        parser_obj.set_debug_level(1);
        parser_obj.set_debug_stream(std::cerr);
    }

    // Parse
    int result = parser_obj.parse();

    // Check result
    if (result == 0) {
        std::cout << "Parse successful!\n";
        
        // Print AST if parsing succeeded
        if (g_program) {
            std::cout << "\nGenerated AST:\n";
            g_program->print();
            // Perform semantic analysis
            analyzer.analyze(*g_program);
            analyzer.print_analysis_results();
            if(analyzer.errors_.size() > 0 ) {
                std::cerr << "Semantic analysis failed with " << analyzer.errors_.size() << " error(s).\n";
                return 1;
            } else {
                std::cout << "Semantic analysis completed successfully with no errors.\n";
            }
        }

        return 0;
    } else {
        std::cerr << "Parse failed with code " << result << std::endl;
        return 1;
    }
}

